[project]
name = "cristalar-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rafael Araújo Novo", email = "rafael.a.novo@criticalsoftware.com" }
]
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.49",
    "openpyxl>=3.1",
    "python-dotenv>=1.0",
    "streamlit>=1.40",
    "platformdirs>=4.0",
]

[project.scripts]
cristalar-faturas = "cristalar_scripts.validar_faturas:main"
cristalar-template = "cristalar_scripts.criar_template:main"
cristalar-ui = "cristalar_scripts.streamlit_app:cli"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
